### ISSUE TITLE
Something should be done if UI.getCurrent is null in the `setOpened` method

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-notification-flow#17]
`public void setOpened(boolean opened)` implementation checks whether the `UI` instance is available and add the component to it. If not it doesn't do anything except calling `super`.

If for some reason there is no `UI` instance available (`UI.getCurrent()` return `null`) then behavior changes and it's hard to understand why (since `UI` is expected implicitly).

It looks like for me that we should throw if there is no `UI` instance.

May be there is no even need to check that `UI.getCurrent()!=null`. Just use it without check which may lead to throw NPE.

Another way may be throwing ISE which detailed explanation why.

If we don't want to throw then at least logging should be done.

@ZheSun88 said that the same code has been used for dialog. Then the similar ticket should be created for the dialog repo and fixed there as well.

**Comment by heruan** [comment]
> If for some reason there is no `UI` instance available

Out of curiosity: in which cases the `UI` may not be present? In FW8 the `UI` wasn't present in `View`s constructors, but in Flow it seems like there always is (empirical statement). Tests, maybe?

**Comment by ZheSun88** [comment]
Same code are used in two different places
dialog: https://github.com/vaadin/vaadin-dialog-flow/blob/master/src/main/java/com/vaadin/flow/component/dialog/Dialog.java#L177

notification: https://github.com/vaadin/vaadin-notification-flow/blob/master/src/main/java/com/vaadin/flow/component/notification/Notification.java#L266

**Comment by denis-anisimov** [comment]
>Out of curiosity: in which cases the UI may not be present? In FW8 the UI wasn't present in Views constructors, but in Flow it seems like there always is (empirical statement). Tests, maybe?

- Test, yes.
- In the CTORs `UI.getCurrent()` should be available if it's in the normal workflow.
- If the code is executed from another thread where `UI.setCurrent()` has not been called (technically outside of correct call `UI.access()`). This is most problematic issue to investigate.
