### ISSUE TITLE
setDuration should use int, not double

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-notification-flow#19]
It's very rare that I want to show a notification for 12.52ms, typically 12ms is enough precision

**Comment by pleku** [comment]
Will be handled by https://github.com/vaadin/flow/issues/3423

**Comment by denis-anisimov** [comment]
Should this ticket be closed then since it's a part of vaadin/flow#3423 ?

**Comment by denis-anisimov** [comment]
Or it should wait for vaadin/flow#3423 and then be done on top of it ?

**Comment by pleku** [comment]
Let's not close this until the PR with API change is in for `Notification`.

**Comment by ZheSun88** [comment]
fixed in https://github.com/vaadin/vaadin-notification-flow/pull/22
