### ISSUE TITLE
helper overload for show method

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/vaadin-notification-flow#25]
Having a helper allowing `Notification.show("Caption")` as in FW8 would be quite handy.

**Comment by mstahv** [comment]
This is a serious annoyance in the API (compared to the old one). Maybe consider fixing this before declaring V10 as our primary product?

**Comment by pleku** [comment]
### Acceptance Criteria
Add convenience method `Notification.show(String text)` that uses the web component defaults for position and duration. Those can be looked up from: https://cdn.vaadin.com/vaadin-notification/1.0.0-beta3/#/elements/vaadin-notification (and described in javadocs).

**Comment by pleku** [comment]
@SomeoneToIgnore @denis-anisimov reopened, please update the demo for static method usage to use the #FFS version that was added. Here https://github.com/vaadin/vaadin-notification-flow/blob/master/src/test/java/com/vaadin/flow/component/notification/demo/NotificationView.java#L71
