### ISSUE TITLE
Redo the notification alignment constructor after a new released version of notification

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/vaadin-notification-flow#4]
in the new version, the alignment will be combined to one property. 
here is the ticket, https://github.com/vaadin/vaadin-notification/pull/34
after it is merged and release, we need to redo that part.

**Comment by pleku** [comment]
The component has been regenerated using the `1.0.0.alpha4` version of the element https://github.com/vaadin/flow/blob/master/flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/notification/GeneratedVaadinNotification.java
