### ISSUE TITLE
Content div should be accessible from Java

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/vaadin-notification-flow#49]
`<vaadin.version>10.0.0.beta7</vaadin.version>`
Currently there's no way of accessing the `<div part="content">` overlay from Java outside of `executeJavascript`. Having access to the element would be needed for, for example, styling the notification.

**Comment by OlliTietavainenVaadin** [comment]
see also this Forum post: https://vaadin.com/forum/thread/17010893

**Comment by pleku** [comment]
The styling for the case mentioned with in the forum post is possible quite easily and we have an example of that https://github.com/vaadin/vaadin-notification-flow/blob/master/src/test/java/com/vaadin/flow/component/notification/demo/NotificationView.java#L109
(it should be available online too on vaadin.com, but there is something wrong, looking into it)

I'm closing this issue for now until more details are provided.

**Comment by mkgl** [comment]
Hi there,

Notification seems to be quite special, in that its mapped element (`<vaadin-notification>`) differs from the one effectively rendering the notification (`<vaadin-notification-card>`) in the container.

Most Java components conveniently have the `#addClassName` method to customize one instance of the component in particular. Here we'd need something to target the card element from server-side. Is this currently possible? (on v12.0.2 for that matter)
