### ISSUE TITLE
Notification is not shown

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-notification-flow#88]
Using 14.0.0.alpha3 and `vaadin-notification-flow` 2.0-SNAPSHOT

Doing `Notification.show("Hello")` adds a `<vaadin-notification>` to the DOM but no notification is shown

**Comment by Legioth** [comment]
Most likely the same root cause as https://github.com/vaadin/flow/issues/5619.

**Comment by Artur-** [comment]
No, even adding `new Notification()` does not fix the problem. Even though it fixes the import problem in https://github.com/vaadin/flow/issues/5619

**Comment by Artur-** [comment]
Seems to have been caused by https://github.com/vaadin/flow/issues/5633
